[SCONE|INFO] src/shielding/crypto.c:222:crypto_get_identity(): Generated enclave certificate
[SCONE|INFO] src/shielding/eai_attestor.c:174:eai_attestor_init(): Created TLS context to communicate with CAS
[SCONE|DEBUG] src/shielding/eai_attestor.c:288:eai_attestor_attest(): Sending Attestation Request to LAS
[SCONE|ERROR] src/shielding/eai_attestor.c:307:eai_attestor_attest(): ATTESTATION: Creating SconeQuote failed at LAS. Won't be able to attest.
[SCONE|WARN] src/process/init.c:466:attest(): Attestation with CAS failed! Error: (null)
[SCONE|WARN] src/process/init.c:627:__scone_prepare_secure_config(): Attestation failed. Retrying in 10 seconds.
sh: unset: line 1: --datadir: bad variable name
[SCONE|INFO] src/shielding/crypto.c:222:crypto_get_identity(): Generated enclave certificate
[SCONE|INFO] src/shielding/eai_attestor.c:174:eai_attestor_init(): Created TLS context to communicate with CAS
[SCONE|DEBUG] src/shielding/eai_attestor.c:288:eai_attestor_attest(): Sending Attestation Request to LAS
[SCONE|ERROR] src/shielding/eai_attestor.c:307:eai_attestor_attest(): ATTESTATION: Creating SconeQuote failed at LAS. Won't be able to attest.
[SCONE|WARN] src/process/init.c:466:attest(): Attestation with CAS failed! Error: (null)
[SCONE|WARN] src/process/init.c:627:__scone_prepare_secure_config(): Attestation failed. Retrying in 10 seconds.
[SCONE|INFO] src/shielding/eai_attestor.c:174:eai_attestor_init(): Created TLS context to communicate with CAS
[SCONE|DEBUG] src/shielding/eai_attestor.c:288:eai_attestor_attest(): Sending Attestation Request to LAS
[SCONE|ERROR] src/shielding/eai_attestor.c:307:eai_attestor_attest(): ATTESTATION: Creating SconeQuote failed at LAS. Won't be able to attest.
[SCONE|WARN] src/process/init.c:466:attest(): Attestation with CAS failed! Error: (null)
[SCONE|WARN] src/process/init.c:627:__scone_prepare_secure_config(): Attestation failed. Retrying in 10 seconds.
[SCONE|INFO] src/shielding/crypto.c:222:crypto_get_identity(): Generated enclave certificate
[SCONE|INFO] src/shielding/eai_attestor.c:174:eai_attestor_init(): Created TLS context to communicate with CAS
[SCONE|DEBUG] src/shielding/eai_attestor.c:288:eai_attestor_attest(): Sending Attestation Request to LAS
[SCONE|ERROR] src/shielding/eai_attestor.c:307:eai_attestor_attest(): ATTESTATION: Creating SconeQuote failed at LAS. Won't be able to attest.
[SCONE|WARN] src/process/init.c:466:attest(): Attestation with CAS failed! Error: (null)
[SCONE|WARN] src/process/init.c:627:__scone_prepare_secure_config(): Attestation failed. Retrying in 10 seconds.
[SCONE|INFO] src/shielding/eai_attestor.c:174:eai_attestor_init(): Created TLS context to communicate with CAS
[SCONE|DEBUG] src/shielding/eai_attestor.c:288:eai_attestor_attest(): Sending Attestation Request to LAS
[SCONE|ERROR] src/shielding/eai_attestor.c:307:eai_attestor_attest(): ATTESTATION: Creating SconeQuote failed at LAS. Won't be able to attest.
[SCONE|WARN] src/process/init.c:466:attest(): Attestation with CAS failed! Error: (null)
[SCONE|WARN] src/process/init.c:627:__scone_prepare_secure_config(): Attestation failed. Retrying in 10 seconds.
[SCONE|INFO] src/shielding/crypto.c:222:crypto_get_identity(): Generated enclave certificate
[SCONE|INFO] src/shielding/eai_attestor.c:174:eai_attestor_init(): Created TLS context to communicate with CAS
[SCONE|DEBUG] src/shielding/eai_attestor.c:288:eai_attestor_attest(): Sending Attestation Request to LAS
[SCONE|ERROR] src/shielding/eai_attestor.c:307:eai_attestor_attest(): ATTESTATION: Creating SconeQuote failed at LAS. Won't be able to attest.
[SCONE|WARN] src/process/init.c:466:attest(): Attestation with CAS failed! Error: (null)
[SCONE|WARN] src/process/init.c:627:__scone_prepare_secure_config(): Attestation failed. Retrying in 10 seconds.
[SCONE|INFO] src/shielding/crypto.c:222:crypto_get_identity(): Generated enclave certificate
[SCONE|INFO] src/shielding/eai_attestor.c:174:eai_attestor_init(): Created TLS context to communicate with CAS
[SCONE|DEBUG] src/shielding/eai_attestor.c:288:eai_attestor_attest(): Sending Attestation Request to LAS
[SCONE|ERROR] src/shielding/eai_attestor.c:307:eai_attestor_attest(): ATTESTATION: Creating SconeQuote failed at LAS. Won't be able to attest.
[SCONE|WARN] src/process/init.c:466:attest(): Attestation with CAS failed! Error: (null)
[SCONE|WARN] src/process/init.c:627:__scone_prepare_secure_config(): Attestation failed. Retrying in 10 seconds.
